// https://github.com/sickdyd/react-flashlight/blob/master/src/ReactFlashlight.js
// https://github.com/sickdyd/react-flashlight-demo/blob/master/src/App.js
import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect } from 'react';
import { ReactFlashlight } from "react-flashlight";
import flashStyle from "../styles/index.module.scss";

// import index from '../pages/index.module.scss'

// export async function getServerSideProps() {
//   const res = await fetch('https://api.jokes.one/knock-knock/random')
//   const joke = await res.json()
//   return {
//     props: {
//       joke
//     }
//   }
// }

const isWindowContext = typeof window !== "undefined";
const Flashlight: NextPage = () => {
  // const { results = [] } = joke
  // console.log(joke);
  // console.log(results);
  const x = isWindowContext && window.innerWidth / 2;
  const y = isWindowContext && window.innerHeight / 2;
  return (
    <div className={flashStyle.fullScreen}>
      <Head>
        <title>Knock Knock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReactFlashlight
        initialPosition={React.useState({ x: x, y: y })[0]}
        size={150}
        // enableMouse={false}
        // showCursor={true}
      >
        <div className={flashStyle.animatedGrid}>
          <div className={flashStyle.k}>
            <h1 className={flashStyle.center}>knock knock...</h1>
          </div>
          <div className={flashStyle.w}>
            <h1 className={flashStyle.center}>who's there...</h1>
          </div>
          <div className={flashStyle.req}>
            <h1 className={flashStyle.center}>ligma</h1>
          </div>
          <div className={flashStyle.res}>
            <h1 className={flashStyle.center}>ligma who?</h1>
          </div>
          <div className={flashStyle.star}>
            <h1 className={flashStyle.center}>ligma balls</h1>
          </div>
        </div>
      </ReactFlashlight>
    </div>
  );
};

export default Flashlight;
