import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { ReactFlashlight } from 'react-flashlight'
import styles from '../styles/Home.module.css'
import index from '../pages/index.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.fullScreen}>
      <Head>
        <title>Flashlight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReactFlashlight>
        <div className={styles.fullScreen}>
          <h1 className={styles.title}>Flashlight</h1>
        </div>
      </ReactFlashlight>
    </div>
  );
}

export default Home