import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import index from '../pages/index.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Flashlight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    </div>
  );
}

export default Home
